/**
 * GeoJSON
 * GeoJSON
 *
 * The version of the OpenAPI document: 0.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type GeometryDto =
    { type: "Point" } & PointDto |
    { type: "LineString" } & LineStringDto |
    { type: "Polygon" } & PolygonDto;

export const GeometryDtoDiscriminators = [
    "Point",
    "LineString",
    "Polygon",
] as const;

export type GeometryDtoDiscriminator = typeof GeometryDtoDiscriminators[number];

/**
 * GeoJSon geometry collection
 */
export interface GeometryCollectionDto {
    type: "GeometryCollection";
    geometries: Array<GeometryDto>;
}

export interface LineStringDto {
    type: "LineString";
    coordinates: Array<[number, number, number?]>;
}

export interface PointDto {
    type: "Point";
    /**
     * Point in 3D space
     */
    coordinates: [number, number, number?];
}

export interface PolygonDto {
    type: "Polygon";
    coordinates: Array<Array<[number, number, number?]>>;
}
